apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: sms-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-app
  template:
    metadata:
      labels:
        app: mongodb-app
    spec:
      containers:
        - name: mongodb-app
          image: mongo:4.4                
          ports:
            - containerPort: 27017
          env:                            
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD  
              value: admin123
          volumeMounts:                   
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
